#!/usr/local/bin/perl -w
###########################################
# google-drive-token-init
# Mike Schilli, 2014 (m@perlmeister.com)
###########################################
use strict;
use lib 'lib';

use OAuth::Cmdline;
use OAuth::Cmdline::Mojo;

my $oauth = OAuth::Cmdline->new(
    client_id     => "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    client_secret => "YYYYYYYYYYYYYYYYYYYYYYYY",
    login_uri     => "https://accounts.google.com/o/oauth2/auth",
    token_uri     => "https://accounts.google.com/o/oauth2/token",
    site          => "google-drive",
    scope         => "https://www.googleapis.com/auth/drive",
);

my $app = OAuth::Cmdline::Mojo->new(
    oauth => $oauth,
);

$app->start( 'daemon', '-l', $oauth->local_uri );
